from __future__ import annotations

MAX_CANDIDATE_STARS = 12
MAX_CLUSTER_COUNT = 4
MAX_CLUSTER_STARS = 12
MAX_TRIANGLE_SEED_STARS = 7
MATCHES_TO_RETURN = 3

TRIANGLE_SIGNATURE_DISTANCE_LIMIT = 0.18
MIN_COMPATIBILITY_SCORE = 0.28
MIN_MATCH_SCORE = 0.5
MIN_MATCH_COVERAGE = 0.5
MIN_LARGE_PATTERN_COVERAGE = 0.54
LARGE_PATTERN_MIN_STARS = 7
MEDIUM_PATTERN_MIN_STARS = 5
MIN_MEDIUM_PATTERN_MATCHED_STARS = 4
MIN_LARGE_PATTERN_MATCHED_STARS = 5
AMBIGUOUS_MATCH_SCORE_MARGIN = 0.08

BRIGHT_STAR_COUNT_TOLERANCE = 3
DETECTED_BRIGHTNESS_QUANTILE = 0.7

ASPECT_RATIO_LOG_TOLERANCE = 0.8
