from __future__ import annotations

MAX_CANDIDATE_STARS = 16
MATCHES_TO_RETURN = 3

TRIANGLE_SIGNATURE_DISTANCE_LIMIT = 0.18
MIN_MATCH_SCORE = 0.54
MIN_MATCH_COVERAGE = 0.55
MIN_LARGE_PATTERN_COVERAGE = 0.58
LARGE_PATTERN_MIN_STARS = 7
AMBIGUOUS_MATCH_SCORE_MARGIN = 0.08

BRIGHT_STAR_COUNT_TOLERANCE = 3
DETECTED_BRIGHTNESS_QUANTILE = 0.7

ASPECT_RATIO_LOG_TOLERANCE = 0.7
